Another change
ibonwe/hello-world pull request #3
Opened 2020-05-10 14:24 UTC by HackerGal

Added a few more lines of code to practice pull and push requests using VS Code.

2020-05-10 20:37 UTC, chadwpetersen commented on python/helloworld.py
> +        print (i)
Add an empty line here.

2020-05-10 20:38 UTC, chadwpetersen requested changes
It is always great to add detail to the pull request description as to what the changes in the code means. What is the code doing -so that I can review it based on that context.

2020-05-10 20:39 UTC, chadwpetersen commented
Also it is always great to create functions so that your code is housed in a file and a function that makes sense.

2020-05-12 00:15 UTC, chadwpetersen requested changes

2020-05-12 00:15 UTC, chadwpetersen commented on python/helloworld.py
> +a= int(input("Insert any number more than 2: "))
I suggest we could have just created another file -called `primelist.py` in this folder and have this code move there and leaving the initial print code in this file. Such that you have two files each serving two different purposes.

2020-05-12 18:32 UTC, HackerGal commented on python/helloworld.py
> +a= int(input("Insert any number more than 2: "))
Separate file made for the primeList function. I hope this is adequate.

2020-05-12 22:40 UTC, chadwpetersen requested changes

2020-05-12 22:40 UTC, chadwpetersen commented on python/helloworld.py
> +a= int(input("Insert any number more than 2: "))
The helloworld file should just print out hello world and the other file should have all of this new code in it.

2020-05-13 18:49 UTC, chadwpetersen approved these changes

2020-05-13 18:49 UTC, merged